name = "doh"
workers_dev = true
# route = "example.com/dns-query"
compatibility_date = "2025-02-09"

main = "index.js"

[placement]
mode = "smart"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
